[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"

[project]
name = "paramclass"
version = "1.1.1"
description = "Parameter class utilities."
readme = "README.md"
requires-python = ">=3.10"
license = "MIT"
license-files = ["license.txt"]
dependencies = []

[project.optional-dependencies]
dev = [
    "pytest",
]

[tool.setuptools.packages.find]
where = ["src"]
